services:
  server:
    image: danmaid/server
    build:
      context: packages/server
    ports:
      - 443:443
    volumes:
      - certs:/usr/local/app/certs:ro
      - ./data:/usr/local/app/data
    environment:
      - CERT_FILE=/usr/local/app/certs/live/danmaid.com/fullchain.pem
      - KEY_FILE=/usr/local/app/certs/live/danmaid.com/privkey.pem
    depends_on:
      certbot:
        condition: service_completed_successfully
    networks:
      default:
        aliases:
          - danmaid.com
  certbot:
    image: certbot/dns-route53
    volumes:
      - certs:/etc/letsencrypt
    command: certonly --dns-route53 -d danmaid.com -d dev.danmaid.com -n --agree-tos --email admin@danmaid.com
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  smtp:
    image: danmaid/smtp
    build:
      context: packages/smtp
    ports:
      - 25:25
    depends_on:
      - server

  uploader:
    profiles:
      - migrate
    image: danmaid/uploader
    build:
      context: packages/uploader
    volumes:
      - uploader:/usr/local/app/public
  rfc822:
    profiles:
      - migrate
    image: danmaid/rfc822
    build:
      context: packages/rfc822
    volumes:
      - rfc822:/app/lib
  migrate:
    profiles:
      - migrate
    image: danmaid/migrate
    build:
      context: packages/migrate
    volumes:
      - ./public:/app/data
      - uploader:/app/modules/uploader:ro
      - rfc822:/app/modules/rfc822:ro
    environment:
      - BASE_URL=https://danmaid.com
    depends_on:
      uploader:
        condition: service_completed_successfully
      rfc822:
        condition: service_completed_successfully

volumes:
  certs:
  uploader:
  rfc822:
