services:
  server:
    image: danmaid/server
    build:
      context: packages/server
    ports:
      - 443:443
    volumes:
      - certs:/usr/local/app/certs:ro
      - ./data:/usr/local/app/data
    environment:
      - CERT_FILE=/usr/local/app/certs/live/dev.danmaid.com/fullchain.pem
      - KEY_FILE=/usr/local/app/certs/live/dev.danmaid.com/privkey.pem
    depends_on:
      certbot:
        condition: service_completed_successfully
    networks:
      default:
        aliases:
          - dev.danmaid.com
  certbot:
    image: certbot/certbot
    ports:
      - 80:80
    volumes:
      - certs:/etc/letsencrypt
    command: certonly --standalone -d dev.danmaid.com -n --agree-tos --email admin@danmaid.com
  uploader:
    image: danmaid/uploader
    build:
      context: packages/uploader
    volumes:
      - uploader:/usr/local/app/public
  migrate:
    image: danmaid/migrate
    build:
      context: .
    volumes:
      - uploader:/app/data:ro
    environment:
      - BASE_URL=https://dev.danmaid.com
    depends_on:
      server:
        condition: service_started
      uploader:
        condition: service_completed_successfully

volumes:
  certs:
  uploader:
