it.todo("POST / { x: 'x', y: 'y', z: 'z' } -> 201 'xxx'(ID)")
it.todo("GET /xxx -> { x: 'x', y: 'y', z: 'z' }")
it.todo("GET / -> ['xxx', 'x', 'y', 'z']")
it.todo("PUT /xxx { x: 'xx', z: 'z', a: 'a' } -> 200")
it.todo("GET /xxx -> { x: 'xx', z: 'z', a: 'a' }")
it.todo("GET / -> ['xxx', 'x', 'z', 'a']")
it.todo("PATCH /xxx { z: 'zz', b: 'b' } -> 200")
it.todo("GET /xxx -> { x: 'xx', z: 'zz', a: 'a', b: 'b' }")
it.todo("GET / -> ['xxx', 'x', 'z', 'a', 'b']")
it.todo('DELETE /xxx -> 200')
it.todo('GET /xxx -> 404')
it.todo('GET / -> []')

it.todo("PUT /yyy { x: 'x', y: 'y', z: 'z' } -> 201")
it.todo('GET / -> { yyy: true }')

it.todo("POST /aaa { x: 'x', y: 'y', z: 'z' } -> 'zzz'(ID)")
it.todo("GET /aaa/zzz -> { x: 'x', y: 'y', z: 'z' }")
it.todo('GET /aaa -> { zzz: true }')
it.todo('GET / -> { yyy: true, aaa: true }')

it.todo('GET / -> { x: true, y: true, z: true }')
it.todo('GET /x -> {}')
it.todo("GET /x/refs -> ['/yyy', '/aaa/zzz']")
it.todo('GET /y -> {}')
it.todo("GET /y/refs -> ['/yyy', '/aaa/zzz']")
it.todo('GET /z -> {}')
it.todo("GET /z/refs -> ['/yyy', '/aaa/zzz']")

it.todo("PUT /bbb { user: 'bbb', url: '/bbb' } -> 200")
it.todo("PUT /ccc { user: 'ccc', url: '/ccc' } -> 200")
it.todo("GET /user -> ['bbb', 'ccc']")
it.todo('GET /user/bbb -> {}')
it.todo("GET /user/bbb/refs -> ['/bbb']")
it.todo('GET /user/ccc -> {}')
it.todo("GET /user/ccc/refs -> ['/ccc']")
it.todo("GET /url -> ['/bbb', '/ccc']")
it.todo('GET /url/%2Fbbb -> {}')
it.todo("GET /url/%2Fbbb/refs -> ['/bbb']")
it.todo('GET /url/%2Fccc -> {}')
it.todo("GET /url/%2Fccc/refs -> ['/ccc']")
it.todo("GET /bbb -> { user: 'bbb', url: '/bbb' }")
it.todo("GET /ccc -> { user: 'ccc', url: '/ccc' }")
it.todo("GET /bbb/refs -> ['/user/bbb', '/url/%2Fbbb']")
it.todo("GET /ccc/refs -> ['/user/ccc', '/url/%2Fccc']")
it.todo("GET / -> ['/bbb', '/user', '/url', '/bbb']")
