configs:
  nginx:
    file: nginx.conf

services:
  front:
    image: nginx:stable
    volumes:
      - contents:/usr/share/nginx/html:ro
      - certs:/etc/certs:ro
    ports:
      - 443:443
    configs:
      - target: /etc/nginx/templates/default.conf.template
        source: nginx
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

  # docker compose run certbot
  certbot:
    profiles:
      - oneshot
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
    command: certonly --standalone --register-unsafely-without-email --agree-tos -d ${DOMAIN_NAME}
    ports:
      - 80:80

  # docker compose run contents
  contents:
    profiles:
      - oneshot
    image: danmaid/sync-tool
    volumes:
      - contents:/mnt/danmaid.com

volumes:
  contents:
  certs:
