name: upload S3
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  S3Upload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: build
        run: |
          npm ci
          npm run build -w packages/events
          npm run build -w packages/blog
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::090737628813:role/github-s3-danmaid.com
          aws-region: us-west-2
      - name: Sync /events
        run: |
          aws s3 sync ./packages/events/dist/ s3://danmaid.com/events/ --delete
          aws s3 sync ./packages/blog/dist/ s3://danmaid.com/blog/ --delete
  DeployEvents:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./packages/events
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/events:latest
