name: tag to release
on:
  push:
    tags:
      - '*'
jobs:
  BuildAndRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build and pack
        run: zip -r $ARCHIVE_NAME public
      - name: create release
        run: gh release create $GITHUB_REF_NAME $ARCHIVE_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCHIVE_NAME: danmaid.com.$GITHUB_REF_NAME.zip
