name: tag to release
on:
  push:
    tags:
      - '*'
jobs:
  BuildAndRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build and pack
        run: zip -r danmaid.com.$GITHUB_REF_NAME.zip public/*
      - name: create release
        run: gh release create $GITHUB_REF_NAME danmaid.com.$GITHUB_REF_NAME.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
