name: tag to release
on:
  push:
    tags:
      - '*'
jobs:
  BuildAndRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build and pack
        run: |
          cd public
          zip -r ../danmaid.com.zip .
      - name: create release
        run: gh release create $GITHUB_REF_NAME danmaid.com.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
