name: sync tool
on:
  push:
    branches:
      - main
    paths:
      - packages/sync/**
jobs:
  PushDockerHub:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: danmaid
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./packages/sync-tool
          push: true
          tags: danmaid/sync-tool:latest
